export const FETCH_TRANSACTIONS_SUCCESS = 'FETCH_TRANSACTIONS_SUCCESS';
export const FETCH_STATISTICS_SUCCESS = 'FETCH_STATISTICS_SUCCESS';
export const FETCH_BAR_CHART_SUCCESS = 'FETCH_BAR_CHART_SUCCESS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_MONTH = 'SET_MONTH';
export const SET_PAGE = 'SET_PAGE';
